use super::{KernelInvocationAdoptionClass, KernelInvocationAdoptionEntry};

use KernelInvocationAdoptionClass::{
    AllowedLocalDirectCommand, KernelDiagnostic, KernelNativeNow,
    MustMigrateToKernelInvocationLater, NotKernelInvocationTarget,
};

pub(crate) const ADOPTION_ENTRIES: &[KernelInvocationAdoptionEntry] = &[
    KernelInvocationAdoptionEntry {
        command: "aicore-cli kernel route <operation>",
        operation: "<operation>",
        class: KernelDiagnostic,
        manifest_capability_exists: true,
        route_runtime_used: true,
        invocation_runtime_used: false,
        ledger_used: false,
        structured_result_envelope_used: false,
        direct_local_execution_allowed_for_now: true,
        future_migration_required: false,
        reason: "route decision diagnostic",
    },
    KernelInvocationAdoptionEntry {
        command: "aicore-cli kernel invoke-smoke <operation>",
        operation: "<operation>",
        class: KernelDiagnostic,
        manifest_capability_exists: true,
        route_runtime_used: true,
        invocation_runtime_used: true,
        ledger_used: true,
        structured_result_envelope_used: false,
        direct_local_execution_allowed_for_now: true,
        future_migration_required: false,
        reason: "dispatcher and ledger diagnostic",
    },
    KernelInvocationAdoptionEntry {
        command: "aicore-cli kernel invoke-readonly runtime.status",
        operation: "runtime.status",
        class: KernelNativeNow,
        manifest_capability_exists: true,
        route_runtime_used: true,
        invocation_runtime_used: true,
        ledger_used: true,
        structured_result_envelope_used: true,
        direct_local_execution_allowed_for_now: false,
        future_migration_required: false,
        reason: "first-party readonly kernel-native path",
    },
    KernelInvocationAdoptionEntry {
        command: "aicore-cli kernel invoke-readonly config.validate",
        operation: "config.validate",
        class: KernelNativeNow,
        manifest_capability_exists: true,
        route_runtime_used: true,
        invocation_runtime_used: true,
        ledger_used: true,
        structured_result_envelope_used: true,
        direct_local_execution_allowed_for_now: false,
        future_migration_required: false,
        reason: "first business readonly local-process kernel-native path",
    },
    KernelInvocationAdoptionEntry {
        command: "aicore-cli kernel invoke-readonly auth.list",
        operation: "auth.list",
        class: KernelNativeNow,
        manifest_capability_exists: true,
        route_runtime_used: true,
        invocation_runtime_used: true,
        ledger_used: true,
        structured_result_envelope_used: true,
        direct_local_execution_allowed_for_now: false,
        future_migration_required: false,
        reason: "auth readonly local-process kernel-native path",
    },
    KernelInvocationAdoptionEntry {
        command: "aicore-cli kernel invoke-readonly model.show",
        operation: "model.show",
        class: KernelNativeNow,
        manifest_capability_exists: true,
        route_runtime_used: true,
        invocation_runtime_used: true,
        ledger_used: true,
        structured_result_envelope_used: true,
        direct_local_execution_allowed_for_now: false,
        future_migration_required: false,
        reason: "model readonly local-process kernel-native path",
    },
    KernelInvocationAdoptionEntry {
        command: "aicore-cli kernel invoke-readonly service.list",
        operation: "service.list",
        class: KernelNativeNow,
        manifest_capability_exists: true,
        route_runtime_used: true,
        invocation_runtime_used: true,
        ledger_used: true,
        structured_result_envelope_used: true,
        direct_local_execution_allowed_for_now: false,
        future_migration_required: false,
        reason: "service readonly local-process kernel-native path",
    },
    KernelInvocationAdoptionEntry {
        command: "aicore-cli kernel invoke-readonly runtime.smoke",
        operation: "runtime.smoke",
        class: KernelNativeNow,
        manifest_capability_exists: true,
        route_runtime_used: true,
        invocation_runtime_used: true,
        ledger_used: true,
        structured_result_envelope_used: true,
        direct_local_execution_allowed_for_now: false,
        future_migration_required: false,
        reason: "runtime smoke readonly local-process kernel-native path",
    },
    KernelInvocationAdoptionEntry {
        command: "aicore-cli kernel invoke-readonly instance.list",
        operation: "instance.list",
        class: KernelNativeNow,
        manifest_capability_exists: true,
        route_runtime_used: true,
        invocation_runtime_used: true,
        ledger_used: true,
        structured_result_envelope_used: true,
        direct_local_execution_allowed_for_now: false,
        future_migration_required: false,
        reason: "instance list readonly local-process kernel-native path",
    },
    KernelInvocationAdoptionEntry {
        command: "aicore-cli kernel invoke-readonly cli.status",
        operation: "cli.status",
        class: KernelNativeNow,
        manifest_capability_exists: true,
        route_runtime_used: true,
        invocation_runtime_used: true,
        ledger_used: true,
        structured_result_envelope_used: true,
        direct_local_execution_allowed_for_now: false,
        future_migration_required: false,
        reason: "CLI status readonly local-process kernel-native path",
    },
    KernelInvocationAdoptionEntry {
        command: "aicore-cli kernel invoke-readonly provider.smoke",
        operation: "provider.smoke",
        class: KernelNativeNow,
        manifest_capability_exists: true,
        route_runtime_used: true,
        invocation_runtime_used: true,
        ledger_used: true,
        structured_result_envelope_used: true,
        direct_local_execution_allowed_for_now: false,
        future_migration_required: false,
        reason: "provider smoke readonly local-process kernel-native path without live provider call",
    },
    KernelInvocationAdoptionEntry {
        command: "aicore-cli status",
        operation: "cli.status",
        class: AllowedLocalDirectCommand,
        manifest_capability_exists: true,
        route_runtime_used: false,
        invocation_runtime_used: false,
        ledger_used: false,
        structured_result_envelope_used: false,
        direct_local_execution_allowed_for_now: true,
        future_migration_required: true,
        reason: "direct compatibility path retained while kernel invoke-readonly cli.status is adopted",
    },
    KernelInvocationAdoptionEntry {
        command: "aicore-cli runtime smoke",
        operation: "runtime.smoke",
        class: AllowedLocalDirectCommand,
        manifest_capability_exists: true,
        route_runtime_used: false,
        invocation_runtime_used: false,
        ledger_used: false,
        structured_result_envelope_used: false,
        direct_local_execution_allowed_for_now: true,
        future_migration_required: true,
        reason: "direct compatibility path retained while kernel invoke-readonly runtime.smoke is adopted",
    },
    KernelInvocationAdoptionEntry {
        command: "aicore-cli instance list",
        operation: "instance.list",
        class: AllowedLocalDirectCommand,
        manifest_capability_exists: true,
        route_runtime_used: false,
        invocation_runtime_used: false,
        ledger_used: false,
        structured_result_envelope_used: false,
        direct_local_execution_allowed_for_now: true,
        future_migration_required: true,
        reason: "local read surface retained until instance readonly adoption",
    },
    KernelInvocationAdoptionEntry {
        command: "aicore-cli config path",
        operation: "config.path",
        class: AllowedLocalDirectCommand,
        manifest_capability_exists: true,
        route_runtime_used: false,
        invocation_runtime_used: false,
        ledger_used: false,
        structured_result_envelope_used: false,
        direct_local_execution_allowed_for_now: true,
        future_migration_required: false,
        reason: "local config path read has low migration priority",
    },
    KernelInvocationAdoptionEntry {
        command: "aicore-cli config init",
        operation: "config.init",
        class: AllowedLocalDirectCommand,
        manifest_capability_exists: false,
        route_runtime_used: false,
        invocation_runtime_used: false,
        ledger_used: false,
        structured_result_envelope_used: false,
        direct_local_execution_allowed_for_now: true,
        future_migration_required: true,
        reason: "bootstrap write command needs explicit config contract",
    },
    KernelInvocationAdoptionEntry {
        command: "aicore-cli config validate",
        operation: "config.validate",
        class: AllowedLocalDirectCommand,
        manifest_capability_exists: true,
        route_runtime_used: false,
        invocation_runtime_used: false,
        ledger_used: false,
        structured_result_envelope_used: false,
        direct_local_execution_allowed_for_now: true,
        future_migration_required: true,
        reason: "direct compatibility path retained while kernel invoke-readonly config.validate is adopted",
    },
    KernelInvocationAdoptionEntry {
        command: "aicore-cli auth list",
        operation: "auth.list",
        class: AllowedLocalDirectCommand,
        manifest_capability_exists: true,
        route_runtime_used: false,
        invocation_runtime_used: false,
        ledger_used: false,
        structured_result_envelope_used: false,
        direct_local_execution_allowed_for_now: true,
        future_migration_required: true,
        reason: "direct compatibility path retained while kernel invoke-readonly auth.list is adopted",
    },
    KernelInvocationAdoptionEntry {
        command: "aicore-cli model show",
        operation: "model.show",
        class: AllowedLocalDirectCommand,
        manifest_capability_exists: true,
        route_runtime_used: false,
        invocation_runtime_used: false,
        ledger_used: false,
        structured_result_envelope_used: false,
        direct_local_execution_allowed_for_now: true,
        future_migration_required: true,
        reason: "direct compatibility path retained while kernel invoke-readonly model.show is adopted",
    },
    KernelInvocationAdoptionEntry {
        command: "aicore-cli service list",
        operation: "service.list",
        class: AllowedLocalDirectCommand,
        manifest_capability_exists: true,
        route_runtime_used: false,
        invocation_runtime_used: false,
        ledger_used: false,
        structured_result_envelope_used: false,
        direct_local_execution_allowed_for_now: true,
        future_migration_required: true,
        reason: "direct compatibility path retained while kernel invoke-readonly service.list is adopted",
    },
    KernelInvocationAdoptionEntry {
        command: "aicore-cli provider smoke",
        operation: "provider.smoke",
        class: AllowedLocalDirectCommand,
        manifest_capability_exists: true,
        route_runtime_used: false,
        invocation_runtime_used: false,
        ledger_used: false,
        structured_result_envelope_used: false,
        direct_local_execution_allowed_for_now: true,
        future_migration_required: true,
        reason: "direct compatibility path retained while kernel invoke-readonly provider.smoke is adopted",
    },
    KernelInvocationAdoptionEntry {
        command: "aicore-cli agent smoke <内容>",
        operation: "agent.smoke",
        class: MustMigrateToKernelInvocationLater,
        manifest_capability_exists: true,
        route_runtime_used: false,
        invocation_runtime_used: false,
        ledger_used: false,
        structured_result_envelope_used: false,
        direct_local_execution_allowed_for_now: false,
        future_migration_required: true,
        reason: "agent capability should flow through runtime invocation",
    },
    KernelInvocationAdoptionEntry {
        command: "aicore-cli agent session-smoke <第一轮内容> <第二轮内容>",
        operation: "agent.session_smoke",
        class: MustMigrateToKernelInvocationLater,
        manifest_capability_exists: true,
        route_runtime_used: false,
        invocation_runtime_used: false,
        ledger_used: false,
        structured_result_envelope_used: false,
        direct_local_execution_allowed_for_now: false,
        future_migration_required: true,
        reason: "agent session capability should flow through runtime invocation",
    },
    KernelInvocationAdoptionEntry {
        command: "aicore-cli memory status",
        operation: "memory.status",
        class: MustMigrateToKernelInvocationLater,
        manifest_capability_exists: true,
        route_runtime_used: false,
        invocation_runtime_used: false,
        ledger_used: false,
        structured_result_envelope_used: false,
        direct_local_execution_allowed_for_now: false,
        future_migration_required: true,
        reason: "memory app read capability should adopt memory contract",
    },
    KernelInvocationAdoptionEntry {
        command: "aicore-cli memory search <关键词>",
        operation: "memory.search",
        class: MustMigrateToKernelInvocationLater,
        manifest_capability_exists: true,
        route_runtime_used: false,
        invocation_runtime_used: false,
        ledger_used: false,
        structured_result_envelope_used: false,
        direct_local_execution_allowed_for_now: false,
        future_migration_required: true,
        reason: "current memory.search invoke-smoke is diagnostic only",
    },
    KernelInvocationAdoptionEntry {
        command: "aicore-cli memory proposals",
        operation: "memory.proposals",
        class: MustMigrateToKernelInvocationLater,
        manifest_capability_exists: true,
        route_runtime_used: false,
        invocation_runtime_used: false,
        ledger_used: false,
        structured_result_envelope_used: false,
        direct_local_execution_allowed_for_now: false,
        future_migration_required: true,
        reason: "memory app read capability should adopt memory contract",
    },
    KernelInvocationAdoptionEntry {
        command: "aicore-cli memory audit",
        operation: "memory.audit",
        class: MustMigrateToKernelInvocationLater,
        manifest_capability_exists: true,
        route_runtime_used: false,
        invocation_runtime_used: false,
        ledger_used: false,
        structured_result_envelope_used: false,
        direct_local_execution_allowed_for_now: false,
        future_migration_required: true,
        reason: "memory audit should adopt memory contract",
    },
    KernelInvocationAdoptionEntry {
        command: "aicore-cli memory wiki [page]",
        operation: "memory.wiki",
        class: MustMigrateToKernelInvocationLater,
        manifest_capability_exists: true,
        route_runtime_used: false,
        invocation_runtime_used: false,
        ledger_used: false,
        structured_result_envelope_used: false,
        direct_local_execution_allowed_for_now: false,
        future_migration_required: true,
        reason: "memory projection read surface should adopt memory contract",
    },
    KernelInvocationAdoptionEntry {
        command: "aicore-cli memory remember <内容>",
        operation: "memory.remember",
        class: MustMigrateToKernelInvocationLater,
        manifest_capability_exists: false,
        route_runtime_used: false,
        invocation_runtime_used: false,
        ledger_used: false,
        structured_result_envelope_used: false,
        direct_local_execution_allowed_for_now: false,
        future_migration_required: true,
        reason: "memory write capability needs memory contract and audit boundary",
    },
    KernelInvocationAdoptionEntry {
        command: "aicore-cli memory accept <proposal_id>",
        operation: "memory.accept",
        class: MustMigrateToKernelInvocationLater,
        manifest_capability_exists: false,
        route_runtime_used: false,
        invocation_runtime_used: false,
        ledger_used: false,
        structured_result_envelope_used: false,
        direct_local_execution_allowed_for_now: false,
        future_migration_required: true,
        reason: "memory write capability needs memory contract and audit boundary",
    },
    KernelInvocationAdoptionEntry {
        command: "aicore-cli memory reject <proposal_id>",
        operation: "memory.reject",
        class: MustMigrateToKernelInvocationLater,
        manifest_capability_exists: false,
        route_runtime_used: false,
        invocation_runtime_used: false,
        ledger_used: false,
        structured_result_envelope_used: false,
        direct_local_execution_allowed_for_now: false,
        future_migration_required: true,
        reason: "memory write capability needs memory contract and audit boundary",
    },
    KernelInvocationAdoptionEntry {
        command: "aicore top-level status",
        operation: "runtime.status",
        class: KernelNativeNow,
        manifest_capability_exists: true,
        route_runtime_used: true,
        invocation_runtime_used: true,
        ledger_used: true,
        structured_result_envelope_used: true,
        direct_local_execution_allowed_for_now: false,
        future_migration_required: false,
        reason: "top-level status consumes runtime.status result envelope",
    },
    KernelInvocationAdoptionEntry {
        command: "cargo foundation",
        operation: "foundation.install",
        class: AllowedLocalDirectCommand,
        manifest_capability_exists: false,
        route_runtime_used: false,
        invocation_runtime_used: false,
        ledger_used: false,
        structured_result_envelope_used: false,
        direct_local_execution_allowed_for_now: true,
        future_migration_required: false,
        reason: "local bootstrap/install workflow",
    },
    KernelInvocationAdoptionEntry {
        command: "cargo kernel",
        operation: "kernel.install",
        class: AllowedLocalDirectCommand,
        manifest_capability_exists: false,
        route_runtime_used: false,
        invocation_runtime_used: false,
        ledger_used: false,
        structured_result_envelope_used: false,
        direct_local_execution_allowed_for_now: true,
        future_migration_required: false,
        reason: "local kernel runtime install workflow",
    },
    KernelInvocationAdoptionEntry {
        command: "cargo core",
        operation: "core.workflow",
        class: AllowedLocalDirectCommand,
        manifest_capability_exists: false,
        route_runtime_used: false,
        invocation_runtime_used: false,
        ledger_used: false,
        structured_result_envelope_used: false,
        direct_local_execution_allowed_for_now: true,
        future_migration_required: false,
        reason: "local aggregate workflow",
    },
    KernelInvocationAdoptionEntry {
        command: "cargo app-*",
        operation: "app.install",
        class: AllowedLocalDirectCommand,
        manifest_capability_exists: false,
        route_runtime_used: false,
        invocation_runtime_used: false,
        ledger_used: false,
        structured_result_envelope_used: false,
        direct_local_execution_allowed_for_now: true,
        future_migration_required: false,
        reason: "local app binary and manifest install workflow",
    },
    KernelInvocationAdoptionEntry {
        command: "help / usage / unknown command",
        operation: "none",
        class: NotKernelInvocationTarget,
        manifest_capability_exists: false,
        route_runtime_used: false,
        invocation_runtime_used: false,
        ledger_used: false,
        structured_result_envelope_used: false,
        direct_local_execution_allowed_for_now: true,
        future_migration_required: false,
        reason: "usage and error text is not a kernel capability invocation",
    },
];
