#[cfg(test)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum KernelInvocationAdoptionClass {
    KernelNativeNow,
    KernelDiagnostic,
    AllowedLocalDirectCommand,
    MustMigrateToKernelInvocationLater,
    NotKernelInvocationTarget,
}

#[cfg(test)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) struct KernelInvocationAdoptionEntry {
    pub(crate) command: &'static str,
    pub(crate) operation: &'static str,
    pub(crate) class: KernelInvocationAdoptionClass,
    pub(crate) manifest_capability_exists: bool,
    pub(crate) route_runtime_used: bool,
    pub(crate) invocation_runtime_used: bool,
    pub(crate) ledger_used: bool,
    pub(crate) structured_result_envelope_used: bool,
    pub(crate) direct_local_execution_allowed_for_now: bool,
    pub(crate) future_migration_required: bool,
    pub(crate) reason: &'static str,
}

#[cfg(test)]
pub(crate) fn kernel_invocation_adoption_matrix() -> &'static [KernelInvocationAdoptionEntry] {
    use KernelInvocationAdoptionClass::{
        AllowedLocalDirectCommand, KernelDiagnostic, KernelNativeNow,
        MustMigrateToKernelInvocationLater, NotKernelInvocationTarget,
    };

    &[
        KernelInvocationAdoptionEntry {
            command: "aicore-cli kernel route <operation>",
            operation: "<operation>",
            class: KernelDiagnostic,
            manifest_capability_exists: true,
            route_runtime_used: true,
            invocation_runtime_used: false,
            ledger_used: false,
            structured_result_envelope_used: false,
            direct_local_execution_allowed_for_now: true,
            future_migration_required: false,
            reason: "route decision diagnostic",
        },
        KernelInvocationAdoptionEntry {
            command: "aicore-cli kernel invoke-smoke <operation>",
            operation: "<operation>",
            class: KernelDiagnostic,
            manifest_capability_exists: true,
            route_runtime_used: true,
            invocation_runtime_used: true,
            ledger_used: true,
            structured_result_envelope_used: false,
            direct_local_execution_allowed_for_now: true,
            future_migration_required: false,
            reason: "dispatcher and ledger diagnostic",
        },
        KernelInvocationAdoptionEntry {
            command: "aicore-cli kernel invoke-readonly runtime.status",
            operation: "runtime.status",
            class: KernelNativeNow,
            manifest_capability_exists: true,
            route_runtime_used: true,
            invocation_runtime_used: true,
            ledger_used: true,
            structured_result_envelope_used: true,
            direct_local_execution_allowed_for_now: false,
            future_migration_required: false,
            reason: "first-party readonly kernel-native path",
        },
        KernelInvocationAdoptionEntry {
            command: "aicore-cli status",
            operation: "system.status",
            class: AllowedLocalDirectCommand,
            manifest_capability_exists: true,
            route_runtime_used: false,
            invocation_runtime_used: false,
            ledger_used: false,
            structured_result_envelope_used: false,
            direct_local_execution_allowed_for_now: true,
            future_migration_required: true,
            reason: "local status surface retained until system status adoption",
        },
        KernelInvocationAdoptionEntry {
            command: "aicore-cli runtime smoke",
            operation: "runtime.smoke",
            class: MustMigrateToKernelInvocationLater,
            manifest_capability_exists: true,
            route_runtime_used: false,
            invocation_runtime_used: false,
            ledger_used: false,
            structured_result_envelope_used: false,
            direct_local_execution_allowed_for_now: false,
            future_migration_required: true,
            reason: "runtime capability smoke should adopt invocation boundary",
        },
        KernelInvocationAdoptionEntry {
            command: "aicore-cli instance list",
            operation: "instance.list",
            class: AllowedLocalDirectCommand,
            manifest_capability_exists: true,
            route_runtime_used: false,
            invocation_runtime_used: false,
            ledger_used: false,
            structured_result_envelope_used: false,
            direct_local_execution_allowed_for_now: true,
            future_migration_required: true,
            reason: "local read surface retained until instance readonly adoption",
        },
        KernelInvocationAdoptionEntry {
            command: "aicore-cli config path",
            operation: "config.path",
            class: AllowedLocalDirectCommand,
            manifest_capability_exists: true,
            route_runtime_used: false,
            invocation_runtime_used: false,
            ledger_used: false,
            structured_result_envelope_used: false,
            direct_local_execution_allowed_for_now: true,
            future_migration_required: false,
            reason: "local config path read has low migration priority",
        },
        KernelInvocationAdoptionEntry {
            command: "aicore-cli config init",
            operation: "config.init",
            class: AllowedLocalDirectCommand,
            manifest_capability_exists: false,
            route_runtime_used: false,
            invocation_runtime_used: false,
            ledger_used: false,
            structured_result_envelope_used: false,
            direct_local_execution_allowed_for_now: true,
            future_migration_required: true,
            reason: "bootstrap write command needs explicit config contract",
        },
        KernelInvocationAdoptionEntry {
            command: "aicore-cli config validate",
            operation: "config.validate",
            class: AllowedLocalDirectCommand,
            manifest_capability_exists: true,
            route_runtime_used: false,
            invocation_runtime_used: false,
            ledger_used: false,
            structured_result_envelope_used: false,
            direct_local_execution_allowed_for_now: true,
            future_migration_required: true,
            reason: "config readonly validation should adopt invocation boundary later",
        },
        KernelInvocationAdoptionEntry {
            command: "aicore-cli auth list",
            operation: "auth.list",
            class: MustMigrateToKernelInvocationLater,
            manifest_capability_exists: true,
            route_runtime_used: false,
            invocation_runtime_used: false,
            ledger_used: false,
            structured_result_envelope_used: false,
            direct_local_execution_allowed_for_now: true,
            future_migration_required: true,
            reason: "auth read surface needs secret-safe invocation boundary",
        },
        KernelInvocationAdoptionEntry {
            command: "aicore-cli model show",
            operation: "model.show",
            class: MustMigrateToKernelInvocationLater,
            manifest_capability_exists: true,
            route_runtime_used: false,
            invocation_runtime_used: false,
            ledger_used: false,
            structured_result_envelope_used: false,
            direct_local_execution_allowed_for_now: true,
            future_migration_required: true,
            reason: "model binding read surface should adopt readonly contract",
        },
        KernelInvocationAdoptionEntry {
            command: "aicore-cli service list",
            operation: "service.list",
            class: MustMigrateToKernelInvocationLater,
            manifest_capability_exists: true,
            route_runtime_used: false,
            invocation_runtime_used: false,
            ledger_used: false,
            structured_result_envelope_used: false,
            direct_local_execution_allowed_for_now: true,
            future_migration_required: true,
            reason: "service profile read surface should adopt readonly contract",
        },
        KernelInvocationAdoptionEntry {
            command: "aicore-cli provider smoke",
            operation: "provider.smoke",
            class: MustMigrateToKernelInvocationLater,
            manifest_capability_exists: true,
            route_runtime_used: false,
            invocation_runtime_used: false,
            ledger_used: false,
            structured_result_envelope_used: false,
            direct_local_execution_allowed_for_now: false,
            future_migration_required: true,
            reason: "provider app capability must not remain direct long term",
        },
        KernelInvocationAdoptionEntry {
            command: "aicore-cli agent smoke <内容>",
            operation: "agent.smoke",
            class: MustMigrateToKernelInvocationLater,
            manifest_capability_exists: true,
            route_runtime_used: false,
            invocation_runtime_used: false,
            ledger_used: false,
            structured_result_envelope_used: false,
            direct_local_execution_allowed_for_now: false,
            future_migration_required: true,
            reason: "agent capability should flow through runtime invocation",
        },
        KernelInvocationAdoptionEntry {
            command: "aicore-cli agent session-smoke <第一轮内容> <第二轮内容>",
            operation: "agent.session_smoke",
            class: MustMigrateToKernelInvocationLater,
            manifest_capability_exists: true,
            route_runtime_used: false,
            invocation_runtime_used: false,
            ledger_used: false,
            structured_result_envelope_used: false,
            direct_local_execution_allowed_for_now: false,
            future_migration_required: true,
            reason: "agent session capability should flow through runtime invocation",
        },
        KernelInvocationAdoptionEntry {
            command: "aicore-cli memory status",
            operation: "memory.status",
            class: MustMigrateToKernelInvocationLater,
            manifest_capability_exists: true,
            route_runtime_used: false,
            invocation_runtime_used: false,
            ledger_used: false,
            structured_result_envelope_used: false,
            direct_local_execution_allowed_for_now: false,
            future_migration_required: true,
            reason: "memory app read capability should adopt memory contract",
        },
        KernelInvocationAdoptionEntry {
            command: "aicore-cli memory search <关键词>",
            operation: "memory.search",
            class: MustMigrateToKernelInvocationLater,
            manifest_capability_exists: true,
            route_runtime_used: false,
            invocation_runtime_used: false,
            ledger_used: false,
            structured_result_envelope_used: false,
            direct_local_execution_allowed_for_now: false,
            future_migration_required: true,
            reason: "current memory.search invoke-smoke is diagnostic only",
        },
        KernelInvocationAdoptionEntry {
            command: "aicore-cli memory proposals",
            operation: "memory.proposals",
            class: MustMigrateToKernelInvocationLater,
            manifest_capability_exists: true,
            route_runtime_used: false,
            invocation_runtime_used: false,
            ledger_used: false,
            structured_result_envelope_used: false,
            direct_local_execution_allowed_for_now: false,
            future_migration_required: true,
            reason: "memory app read capability should adopt memory contract",
        },
        KernelInvocationAdoptionEntry {
            command: "aicore-cli memory audit",
            operation: "memory.audit",
            class: MustMigrateToKernelInvocationLater,
            manifest_capability_exists: true,
            route_runtime_used: false,
            invocation_runtime_used: false,
            ledger_used: false,
            structured_result_envelope_used: false,
            direct_local_execution_allowed_for_now: false,
            future_migration_required: true,
            reason: "memory audit should adopt memory contract",
        },
        KernelInvocationAdoptionEntry {
            command: "aicore-cli memory wiki [page]",
            operation: "memory.wiki",
            class: MustMigrateToKernelInvocationLater,
            manifest_capability_exists: true,
            route_runtime_used: false,
            invocation_runtime_used: false,
            ledger_used: false,
            structured_result_envelope_used: false,
            direct_local_execution_allowed_for_now: false,
            future_migration_required: true,
            reason: "memory projection read surface should adopt memory contract",
        },
        KernelInvocationAdoptionEntry {
            command: "aicore-cli memory remember <内容>",
            operation: "memory.remember",
            class: MustMigrateToKernelInvocationLater,
            manifest_capability_exists: false,
            route_runtime_used: false,
            invocation_runtime_used: false,
            ledger_used: false,
            structured_result_envelope_used: false,
            direct_local_execution_allowed_for_now: false,
            future_migration_required: true,
            reason: "memory write capability needs memory contract and audit boundary",
        },
        KernelInvocationAdoptionEntry {
            command: "aicore-cli memory accept <proposal_id>",
            operation: "memory.accept",
            class: MustMigrateToKernelInvocationLater,
            manifest_capability_exists: false,
            route_runtime_used: false,
            invocation_runtime_used: false,
            ledger_used: false,
            structured_result_envelope_used: false,
            direct_local_execution_allowed_for_now: false,
            future_migration_required: true,
            reason: "memory write capability needs memory contract and audit boundary",
        },
        KernelInvocationAdoptionEntry {
            command: "aicore-cli memory reject <proposal_id>",
            operation: "memory.reject",
            class: MustMigrateToKernelInvocationLater,
            manifest_capability_exists: false,
            route_runtime_used: false,
            invocation_runtime_used: false,
            ledger_used: false,
            structured_result_envelope_used: false,
            direct_local_execution_allowed_for_now: false,
            future_migration_required: true,
            reason: "memory write capability needs memory contract and audit boundary",
        },
        KernelInvocationAdoptionEntry {
            command: "aicore top-level status",
            operation: "runtime.status",
            class: KernelNativeNow,
            manifest_capability_exists: true,
            route_runtime_used: true,
            invocation_runtime_used: true,
            ledger_used: true,
            structured_result_envelope_used: true,
            direct_local_execution_allowed_for_now: false,
            future_migration_required: false,
            reason: "top-level status consumes runtime.status result envelope",
        },
        KernelInvocationAdoptionEntry {
            command: "cargo foundation",
            operation: "foundation.install",
            class: AllowedLocalDirectCommand,
            manifest_capability_exists: false,
            route_runtime_used: false,
            invocation_runtime_used: false,
            ledger_used: false,
            structured_result_envelope_used: false,
            direct_local_execution_allowed_for_now: true,
            future_migration_required: false,
            reason: "local bootstrap/install workflow",
        },
        KernelInvocationAdoptionEntry {
            command: "cargo kernel",
            operation: "kernel.install",
            class: AllowedLocalDirectCommand,
            manifest_capability_exists: false,
            route_runtime_used: false,
            invocation_runtime_used: false,
            ledger_used: false,
            structured_result_envelope_used: false,
            direct_local_execution_allowed_for_now: true,
            future_migration_required: false,
            reason: "local kernel runtime install workflow",
        },
        KernelInvocationAdoptionEntry {
            command: "cargo core",
            operation: "core.workflow",
            class: AllowedLocalDirectCommand,
            manifest_capability_exists: false,
            route_runtime_used: false,
            invocation_runtime_used: false,
            ledger_used: false,
            structured_result_envelope_used: false,
            direct_local_execution_allowed_for_now: true,
            future_migration_required: false,
            reason: "local aggregate workflow",
        },
        KernelInvocationAdoptionEntry {
            command: "cargo app-*",
            operation: "app.install",
            class: AllowedLocalDirectCommand,
            manifest_capability_exists: false,
            route_runtime_used: false,
            invocation_runtime_used: false,
            ledger_used: false,
            structured_result_envelope_used: false,
            direct_local_execution_allowed_for_now: true,
            future_migration_required: false,
            reason: "local app binary and manifest install workflow",
        },
        KernelInvocationAdoptionEntry {
            command: "help / usage / unknown command",
            operation: "none",
            class: NotKernelInvocationTarget,
            manifest_capability_exists: false,
            route_runtime_used: false,
            invocation_runtime_used: false,
            ledger_used: false,
            structured_result_envelope_used: false,
            direct_local_execution_allowed_for_now: true,
            future_migration_required: false,
            reason: "usage and error text is not a kernel capability invocation",
        },
    ]
}
