use super::super::KernelInvocationAdoptionClass::AllowedLocalDirectCommand;
use super::super::KernelInvocationAdoptionEntry;
use super::entry;

pub(super) const ENTRIES: &[KernelInvocationAdoptionEntry] = &[
    entry(
        "aicore-cli status",
        "cli.status",
        AllowedLocalDirectCommand,
        true,
        false,
        false,
        false,
        false,
        true,
        true,
        "direct compatibility path retained while kernel invoke-readonly cli.status is adopted",
    ),
    entry(
        "aicore-cli runtime smoke",
        "runtime.smoke",
        AllowedLocalDirectCommand,
        true,
        false,
        false,
        false,
        false,
        true,
        true,
        "direct compatibility path retained while kernel invoke-readonly runtime.smoke is adopted",
    ),
    entry(
        "aicore-cli instance list",
        "instance.list",
        AllowedLocalDirectCommand,
        true,
        false,
        false,
        false,
        false,
        true,
        true,
        "local read surface retained until instance readonly adoption",
    ),
    entry(
        "aicore-cli config path",
        "config.path",
        AllowedLocalDirectCommand,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        "local config path read has low migration priority",
    ),
    entry(
        "aicore-cli config init",
        "config.init",
        AllowedLocalDirectCommand,
        false,
        false,
        false,
        false,
        false,
        true,
        true,
        "bootstrap write command needs explicit config contract",
    ),
    entry(
        "aicore-cli config validate",
        "config.validate",
        AllowedLocalDirectCommand,
        true,
        false,
        false,
        false,
        false,
        true,
        true,
        "direct compatibility path retained while kernel invoke-readonly config.validate is adopted",
    ),
    entry(
        "aicore-cli auth list",
        "auth.list",
        AllowedLocalDirectCommand,
        true,
        false,
        false,
        false,
        false,
        true,
        true,
        "direct compatibility path retained while kernel invoke-readonly auth.list is adopted",
    ),
    entry(
        "aicore-cli model show",
        "model.show",
        AllowedLocalDirectCommand,
        true,
        false,
        false,
        false,
        false,
        true,
        true,
        "direct compatibility path retained while kernel invoke-readonly model.show is adopted",
    ),
    entry(
        "aicore-cli service list",
        "service.list",
        AllowedLocalDirectCommand,
        true,
        false,
        false,
        false,
        false,
        true,
        true,
        "direct compatibility path retained while kernel invoke-readonly service.list is adopted",
    ),
    entry(
        "aicore-cli provider smoke",
        "provider.smoke",
        AllowedLocalDirectCommand,
        true,
        false,
        false,
        false,
        false,
        true,
        true,
        "direct compatibility path retained while kernel invoke-readonly provider.smoke is adopted",
    ),
    entry(
        "aicore-cli agent smoke <内容>",
        "agent.smoke",
        AllowedLocalDirectCommand,
        true,
        false,
        false,
        false,
        false,
        true,
        true,
        "direct compatibility path retained while kernel invoke-readonly agent.smoke is adopted",
    ),
    entry(
        "aicore-cli agent session-smoke <第一轮内容> <第二轮内容>",
        "agent.session_smoke",
        AllowedLocalDirectCommand,
        true,
        false,
        false,
        false,
        false,
        true,
        true,
        "direct compatibility path retained while kernel invoke-readonly agent.session_smoke is adopted",
    ),
];
