use super::super::KernelInvocationAdoptionClass::MustMigrateToKernelInvocationLater;
use super::super::KernelInvocationAdoptionEntry;
use super::entry;

pub(super) const ENTRIES: &[KernelInvocationAdoptionEntry] = &[
    entry(
        "aicore-cli memory status",
        "memory.status",
        MustMigrateToKernelInvocationLater,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        "memory app read capability should adopt memory contract",
    ),
    entry(
        "aicore-cli memory search <关键词>",
        "memory.search",
        MustMigrateToKernelInvocationLater,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        "current memory.search invoke-smoke is diagnostic only",
    ),
    entry(
        "aicore-cli memory proposals",
        "memory.proposals",
        MustMigrateToKernelInvocationLater,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        "memory app read capability should adopt memory contract",
    ),
    entry(
        "aicore-cli memory audit",
        "memory.audit",
        MustMigrateToKernelInvocationLater,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        "memory audit should adopt memory contract",
    ),
    entry(
        "aicore-cli memory wiki [page]",
        "memory.wiki",
        MustMigrateToKernelInvocationLater,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        "memory projection read surface should adopt memory contract",
    ),
    entry(
        "aicore-cli memory remember <内容>",
        "memory.remember",
        MustMigrateToKernelInvocationLater,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        "memory write capability needs memory contract and audit boundary",
    ),
    entry(
        "aicore-cli memory accept <proposal_id>",
        "memory.accept",
        MustMigrateToKernelInvocationLater,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        "memory write capability needs memory contract and audit boundary",
    ),
    entry(
        "aicore-cli memory reject <proposal_id>",
        "memory.reject",
        MustMigrateToKernelInvocationLater,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        "memory write capability needs memory contract and audit boundary",
    ),
];
