use super::super::KernelInvocationAdoptionClass::KernelNativeNow;
use super::super::KernelInvocationAdoptionEntry;
use super::entry;

pub(super) const ENTRIES: &[KernelInvocationAdoptionEntry] = &[
    entry(
        "aicore-cli kernel invoke-readonly runtime.status",
        "runtime.status",
        KernelNativeNow,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        "first-party readonly kernel-native path",
    ),
    entry(
        "aicore-cli kernel invoke-readonly config.validate",
        "config.validate",
        KernelNativeNow,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        "first business readonly local-process kernel-native path",
    ),
    entry(
        "aicore-cli kernel invoke-readonly auth.list",
        "auth.list",
        KernelNativeNow,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        "auth readonly local-process kernel-native path",
    ),
    entry(
        "aicore-cli kernel invoke-readonly model.show",
        "model.show",
        KernelNativeNow,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        "model readonly local-process kernel-native path",
    ),
    entry(
        "aicore-cli kernel invoke-readonly service.list",
        "service.list",
        KernelNativeNow,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        "service readonly local-process kernel-native path",
    ),
    entry(
        "aicore-cli kernel invoke-readonly runtime.smoke",
        "runtime.smoke",
        KernelNativeNow,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        "runtime smoke readonly local-process kernel-native path",
    ),
    entry(
        "aicore-cli kernel invoke-readonly instance.list",
        "instance.list",
        KernelNativeNow,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        "instance list readonly local-process kernel-native path",
    ),
    entry(
        "aicore-cli kernel invoke-readonly cli.status",
        "cli.status",
        KernelNativeNow,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        "CLI status readonly local-process kernel-native path",
    ),
    entry(
        "aicore-cli kernel invoke-readonly provider.smoke",
        "provider.smoke",
        KernelNativeNow,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        "provider smoke readonly local-process kernel-native path without live provider call",
    ),
    entry(
        "aicore-cli kernel invoke-readonly agent.smoke",
        "agent.smoke",
        KernelNativeNow,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        "agent smoke readonly local-process kernel-native path without real provider",
    ),
    entry(
        "aicore-cli kernel invoke-readonly agent.session_smoke",
        "agent.session_smoke",
        KernelNativeNow,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        "agent session smoke readonly local-process kernel-native path without real provider",
    ),
    entry(
        "aicore-cli kernel invoke-readonly memory.status",
        "memory.status",
        KernelNativeNow,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        "memory status readonly local-process kernel-native path",
    ),
    entry(
        "aicore-cli kernel invoke-readonly memory.search",
        "memory.search",
        KernelNativeNow,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        "memory search readonly local-process kernel-native path",
    ),
    entry(
        "aicore-cli kernel invoke-readonly memory.proposals",
        "memory.proposals",
        KernelNativeNow,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        "memory proposals readonly local-process kernel-native path",
    ),
    entry(
        "aicore-cli kernel invoke-readonly memory.audit",
        "memory.audit",
        KernelNativeNow,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        "memory audit readonly local-process kernel-native path",
    ),
    entry(
        "aicore-cli kernel invoke-readonly memory.wiki",
        "memory.wiki",
        KernelNativeNow,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        "memory wiki readonly local-process kernel-native path",
    ),
    entry(
        "aicore-cli kernel invoke-readonly memory.wiki_page",
        "memory.wiki_page",
        KernelNativeNow,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        "memory wiki page readonly local-process kernel-native path",
    ),
    entry(
        "aicore top-level status",
        "runtime.status",
        KernelNativeNow,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        "top-level status consumes runtime.status result envelope",
    ),
];
