use super::super::KernelInvocationAdoptionClass::{
    AllowedLocalDirectCommand, NotKernelInvocationTarget,
};
use super::super::KernelInvocationAdoptionEntry;
use super::entry;

pub(super) const ENTRIES: &[KernelInvocationAdoptionEntry] = &[
    entry(
        "cargo foundation",
        "foundation.install",
        AllowedLocalDirectCommand,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        "local bootstrap/install workflow",
    ),
    entry(
        "cargo kernel",
        "kernel.install",
        AllowedLocalDirectCommand,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        "local kernel runtime install workflow",
    ),
    entry(
        "cargo core",
        "core.workflow",
        AllowedLocalDirectCommand,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        "local aggregate workflow",
    ),
    entry(
        "cargo app-*",
        "app.install",
        AllowedLocalDirectCommand,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        "local app binary and manifest install workflow",
    ),
    entry(
        "help / usage / unknown command",
        "none",
        NotKernelInvocationTarget,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        "usage and error text is not a kernel capability invocation",
    ),
];
